FROM mysql
# ENV MYSQL_DATABASE: portfolioDB
# ENV MYSQL_USER: root
# ENV MYSQL_PASSWORD: password
# ENV MYSQL_ROOT_USER: root
# ENV MYSQL_ROOT_PASSWORD: password

# ADD ./init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306