version: '3.9'
services:
  apache:
    container_name: apache
    build:
      context: ./WebService/apache
      dockerfile: Dockerfile
    volumes:
      - './WebService/apache:/var/www/html/'

    ports:
      - 80:80
    depends_on:
      - database1
      - nginx

  nginx:
    container_name: nginx
    build:
      context: ./WebService/nginx
      dockerfile: Dockerfile
    volumes:
      - ./WebService/nginx/html:/usr/share/nginx/html
      - ./WebService/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - database1
      
  database1:
    container_name: database1
    build: 
      context: ./WebService/database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./WebService/database/:/docker-entrypoint-initdb.d