version: '3.9'
services:
  apache:
    build:
      context: ./WebService/apache
      dockerfile: Dockerfile
    # restart: always
    volumes:
      - './WebService/apache:/var/www/html/'
      # - ./WebService/apache/apache2.conf:/etc/apache2/apache2.conf

    ports:
      - 80:80
    # network_mode: host
    depends_on:
      - db
      - nginx

  nginx:
    container_name: nginx
    build:
      context: ./WebService/nginx
      dockerfile: Dockerfile
    # restart: always
    # links:
    #   - database
    volumes:
      - ./WebService/nginx/html:/usr/share/nginx/html
      - ./WebService/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - db
      
  db:
    build: 
      context: ./WebService/database
      dockerfile: Dockerfile
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: portfolioDB
    volumes:
      - ./WebService/database/:/docker-entrypoint-initdb.d
    # ports:
    #   - 3307:33060
    # restart: always 
